name: Keep Alive Renca FC

on:
  schedule:
    - cron: '0 0,12 * * *' # Se ejecuta a las 00:00 y 12:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend API
        run: |
          curl -I https://renca-fc.onrender.com/clubs
          echo "Pulse sent to Render and Supabase"
